### PR TITLE
Fix unexpected cache error

### LINKED ISSUE #420: Unexpected Error `SET_DATASET_FIELDS_IN_CACHE_FAILED` in logs
I see this error in the logs all the time

```
[18:48:03 UTC] ERROR: [Express POST] SET_DATASET_FIELDS_IN_CACHE_FAILED [6b86fe21-d0d1-4318-8e97-dfa0d6b91ae9]
    extra: {}
    err: {
      "type": "InvalidErrorObject"
    }
```

Two problems:

1. incorrect parsing of the error message (“InvalidErrorObject”)
2. this happens when the cache is disabled

```
redis: null
```

No need to try to connect to Redis if you don't have one.

### PR DESCRIPTION
**Pull request by melikhov-dev**
fixes #420

### CODE REVIEW

File: src/server/modes/charts/plugins/request-with-dataset/request-dataset.ts [hunk 1]
```diff
@@ -81,15 +81,47 @@ export const getDatasetFields = async (args: {
...
+                    key: cacheKey,
+                    ttl: pluginOptions?.cache || DEFAULT_CACHE_TTL,
+                    value: {datasetFields, revisionId},
+                })
+                .then((setCacheResponse) => {
+                    if (setCacheResponse.status === Cache.OK) {
+                        req.ctx.log('SET_DATASET_IN_CACHE_SUCCESS');
+                    } else {
+                        req.ctx.logError('SET_DATASET_FIELDS_IN_CACHE_FAILED', setCacheResponse);
+                        req.ctx.logError(
```
Comment (jhoncool) [inline src/server/modes/charts/plugins/request-with-dataset/request-dataset.ts:114]: Is it necessary to log error twice?

**Review by jhoncool — DISMISSED** [review]

**Review by jhoncool — APPROVED** [review]

File: src/server/modes/charts/plugins/request-with-dataset/request-dataset.ts (hunk 1 above)
Comment (melikhov-dev) [reply src/server/modes/charts/plugins/request-with-dataset/request-dataset.ts:113]: @jhoncool Oh, just an artifact. Removed it in e3f4431986
